#!/usr/bin/env bash
# Regenerate /etc/nvr-prototype/nginx-archive-accel.conf from archive.root_path in
# /etc/nvr-prototype/nvr.yaml so nginx `alias` matches the daemon (X-Accel-Redirect).
# Run as root after changing archive path; then: nginx -t && systemctl reload nginx
set -euo pipefail

CFG="${NVR_CONFIG_YAML:-/etc/nvr-prototype/nvr.yaml}"
OUT="${NVR_NGINX_ARCHIVE_SNIPPET:-/etc/nvr-prototype/nginx-archive-accel.conf}"
DEFAULT="/var/lib/nvr-prototype/archive"

extract_root() {
  local root=""
  if [[ -f "$CFG" ]]; then
    root="$(
      awk '
        /^archive:/ { a = 1; next }
        a && /^[^[:space:]]/ { exit }
        a && /^  root_path:/ {
          sub(/^  root_path:[[:space:]]*/, "")
          gsub(/["'\'']/, "", $0)
          print
          exit
        }
      ' "$CFG" 2>/dev/null || true
    )"
  fi
  if [[ -z "${root}" ]]; then
    root="${DEFAULT}"
  fi
  case "${root}" in
  */) printf '%s' "${root}" ;;
  *) printf '%s/' "${root}" ;;
  esac
}

ROOT="$(extract_root)"
TMP="${OUT}.tmp"
mkdir -p "$(dirname "${OUT}")"
umask 022
cat >"${TMP}" <<EOF
# Generated by nvr_sync_nginx_archive_accel.sh — do not edit by hand.
# Source: archive.root_path in ${CFG}
location /_nvr_accel/ {
    internal;
    alias ${ROOT};
}
EOF
mv -f "${TMP}" "${OUT}"
echo "Wrote ${OUT} (alias -> ${ROOT})"
